# Define.py

MAINWINDOWTITLE="PoseLibrary"
MAINWINDOWSIZEX=510
MAINWINDOWSIZEY=700

DATAUPPATH = "/Users/yamashiromiki/Documents/Data/PoseLibrary"
CAPTUREFOLDER = "image"
JSONFOLDER = "json"
FRAMEBUFFER_WIDTH=400
FRAMEBUFFER_HEIGHT=200
