# Define.py

MAINWINDOWTITLE="PoseLibrary"
MAINWINDOWSIZEX=510
MAINWINDOWSIZEY=800

DATAUPPATH = ""
CAPTUREFOLDER = "image"
JSONFOLDER = "json"
FRAMEBUFFER_WIDTH=400
FRAMEBUFFER_HEIGHT=200

WINDOW_NAME = "ym_pose_library_ui"
WINDOW_TITLE = "PoseLibrary"